### ISSUE TITLE
unnamed struct is disabled in default

### ISSUE THREAD

**Issue by mattn** [cznic/99c#2]
```c
#include <windows.h>

int main(int argc, char* argv[]) {
  MessageBox(0, "foo", "bar", MB_OK);
  return 0;
}
```
This make error

```
c:\dev\godev\src\github.com\cznic\ccir\libc\windows_windows_amd64.h:1874:3: unnamed fields not allowed
```

This seems to be enabled with `cc.EnableAnonymousStructFields()` but if I add this option into 99c/main.go, TODO error occured.

```diff
diff --git a/main.go b/main.go
index 7edb065..5c2e01f 100644
--- a/main.go
+++ b/main.go
@@ -196,6 +196,7 @@ func (t *task) main() error {
 			model,
 			cc.IncludePaths(t.args.I),
 			cc.SysIncludePaths([]string{ccir.LibcIncludePath}),
+			cc.EnableAnonymousStructFields(),
 			cc.AllowCompatibleTypedefRedefinitions(),
 			cc.Cpp(func(toks []xc.Token) {
 				if len(toks) != 0 {
@@ -249,6 +250,7 @@ func (t *task) main() error {
 				model,
 				cc.IncludePaths(t.args.I),
 				cc.SysIncludePaths([]string{ccir.LibcIncludePath}),
+				cc.EnableAnonymousStructFields(),
 				cc.AllowCompatibleTypedefRedefinitions(),
 			)
 			if err != nil {
@@ -297,6 +299,7 @@ func (t *task) main() error {
 			model,
 			cc.IncludePaths(t.args.I),
 			cc.SysIncludePaths([]string{ccir.LibcIncludePath}),
+			cc.EnableAnonymousStructFields(),
 			cc.AllowCompatibleTypedefRedefinitions(),
 		)
 		if err != nil {
```

```
99c: PANIC: c:\dev\godev\src\github.com\cznic\ccir\libc\windows_windows_amd64.h:2456:9: TODO
goroutine 1 [running]:
runtime/debug.Stack(0xc042cdc7b8, 0x65e460, 0xc04300ed70)
	c:/dev/go/src/runtime/debug/stack.go:24 +0xae
main.main.func1()
	c:/dev/godev/src/github.com/cznic/99c/main.go:34 +0x67
panic(0x65e460, 0xc04300ed70)
	c:/dev/go/src/runtime/panic.go:502 +0x274
github.com/cznic/cc.(*StructOrUnionSpecifier).isCompatible(0xc043027680, 0xc043027620, 0x1c930)
	c:/dev/godev/src/github.com/cznic/cc/ast2.go:3397 +0x79f
github.com/cznic/cc.(*Bindings).defineStructTag(0xc0421fc090, 0x154000000e021, 0x1c930, 0x6eafa0, 0xc043027680, 0xc0421e20c0)
	c:/dev/godev/src/github.com/cznic/cc/etc.go:422 +0x175
github.com/cznic/cc.yyParse(0x6eb700, 0xc04206ac00, 0x0)
	c:/dev/godev/src/github.com/cznic/cc/parser.go:3841 +0xd528
github.com/cznic/cc.Parse(0xc042199090, 0x45, 0xc0421ccac0, 0x2, 0x2, 0xc0421f2000, 0xc042069d20, 0x4, 0x4, 0x32, ...)
	c:/dev/godev/src/github.com/cznic/cc/cc.go:808 +0x692
main.(*task).main(0xc042cddec0, 0x0, 0x0)
	c:/dev/godev/src/github.com/cznic/99c/main.go:291 +0x13c1
main.main()
	c:/dev/godev/src/github.com/cznic/99c/main.go:40 +0xb2

:**

**Comment by mattn** [comment]
This is the part pointed from errors.

```c
typedef struct _XSTATE_CONFIGURATION {
	DWORD64 EnabledFeatures;
	DWORD64 EnabledVolatileFeatures;
	DWORD Size;
	DWORD OptimizedSave:1;
	XSTATE_FEATURE Features[64];
} XSTATE_CONFIGURATION;
typedef struct _XSTATE_CONFIGURATION {
	DWORD64 EnabledFeatures;
	DWORD64 EnabledVolatileFeatures;
	DWORD Size;
	DWORD OptimizedSave:1;
	XSTATE_FEATURE Features[64];
} *PXSTATE_CONFIGURATION;
```

**Comment by cznic** [comment]
@mattn 

IIRC, anonymous structs are not legal in C99, however C11 has them. We need a command line flag enabling them.

Either `-std=c11` or a particular like `-99anonymousstructs`. The later is probably better because I recall always enabling all the CC options was not working for some C projects (don't remember which).

WDYT?

The stack trace points probably to some outdated version of cc, [github.com/cznic/cc/ast2.go:3397](https://github.com/cznic/cc/blob/59191bccf71159ab473547bfd8cc908dadd3b716/ast2.go#L3397). Please update 99c by `go get -u github.com/cznic/cc` and if the TODO panic still occurs then please fill an issue in the CC repository. Thank you.

**Comment by mattn** [comment]
Sorry, this is my wrong. Now I got new error

```
c:\dev\godev\src\github.com\cznic\ccir\libc\windows_windows_amd64.h:4976:19: bit field has invalid type (have unsigned long long)
c:\dev\godev\src\github.com\cznic\ccir\libc\windows_windows_amd64.h:4977:22: bit field has invalid type (have unsigned long long)
c:\dev\godev\src\github.com\cznic\ccir\libc\windows_windows_amd64.h:4978:23: bit field has invalid type (have unsigned long long)
c:\dev\godev\src\github.com\cznic\ccir\libc\windows_windows_amd64.h:4979:24: bit field has invalid type (have unsigned long long)
c:\dev\godev\src\github.com\cznic\ccir\libc\windows_windows_amd64.h:4980:18: bit field has invalid type (have unsigned long long)
c:\dev\godev\src\github.com\cznic\ccir\libc\windows_windows_amd64.h:4981:22: bit field has invalid type (have unsigned long long)
c:\dev\godev\src\github.com\cznic\ccir\libc\windows_windows_amd64.h:4982:20: bit field has invalid type (have unsigned long long)
c:\dev\godev\src\github.com\cznic\ccir\libc\windows_windows_amd64.h:4985:19: bit field has invalid type (have unsigned long long)
c:\dev\godev\src\github.com\cznic\ccir\libc\windows_windows_amd64.h:4986:22: bit field has invalid type (have unsigned long long)
c:\dev\godev\src\github.com\cznic\ccir\libc\windows_windows_amd64.h:4987:24: bit field has invalid type (have unsigned long long)
2017/10/09 21:46:00 too many errors
```
cc seems support bit field. (of cause, I need to add new flag -99anonymous)

**Comment by mattn** [comment]
```
typedef union _SLIST_HEADER {
	struct {
		ULONGLONG Alignment;
		ULONGLONG Region;
	};
	struct {
		ULONGLONG Depth:16;
		ULONGLONG Sequence:9;
		ULONGLONG NextEntry:39;
		ULONGLONG HeaderType:1;
		ULONGLONG Init:1;
		ULONGLONG Reserved:59;
		ULONGLONG Region:3;
	} Header8;
	struct {
		ULONGLONG Depth:16;
		ULONGLONG Sequence:48;
		ULONGLONG HeaderType:1;
		ULONGLONG Reserved:3;
		ULONGLONG NextEntry:60;
	} HeaderX64;
} SLIST_HEADER;
```
ULONGLONG is defined like below
```c
   274	typedef unsigned long long ULONGLONG;
```

**Comment by cznic** [comment]
@mattn 

Bit fields are specified such that they must fit into a C `int`. However longer bit fields can be enabled by some CC.Option, please check which one it is, can't recall it now.

Please suggest the new comman-line options or feel free to make a branch for it and a PR for me to review. Please wait for the review before merging into master, thank you.

**Comment by mattn** [comment]
Ah, cc have cc.EnableWideBitFieldTypes(). already. right?

**Comment by cznic** [comment]
I believe it's the right option for that.

**Comment by mattn** [comment]
Cool. Now I could compile it.

```diff
diff --git a/main.go b/main.go
index 7edb065..85549df 100644
--- a/main.go
+++ b/main.go
@@ -196,6 +196,8 @@ func (t *task) main() error {
 			model,
 			cc.IncludePaths(t.args.I),
 			cc.SysIncludePaths([]string{ccir.LibcIncludePath}),
+			cc.EnableAnonymousStructFields(),
+			cc.EnableWideBitFieldTypes(),
 			cc.AllowCompatibleTypedefRedefinitions(),
 			cc.Cpp(func(toks []xc.Token) {
 				if len(toks) != 0 {
@@ -249,6 +251,8 @@ func (t *task) main() error {
 				model,
 				cc.IncludePaths(t.args.I),
 				cc.SysIncludePaths([]string{ccir.LibcIncludePath}),
+				cc.EnableAnonymousStructFields(),
+				cc.EnableWideBitFieldTypes(),
 				cc.AllowCompatibleTypedefRedefinitions(),
 			)
 			if err != nil {
@@ -297,6 +301,8 @@ func (t *task) main() error {
 			model,
 			cc.IncludePaths(t.args.I),
 			cc.SysIncludePaths([]string{ccir.LibcIncludePath}),
+			cc.EnableAnonymousStructFields(),
+			cc.EnableWideBitFieldTypes(),
 			cc.AllowCompatibleTypedefRedefinitions(),
 		)
 		if err != nil {
```
-99widebitfield or something required. Now I got linkage error. I modifed code like below.

```c
#include <windows.h>

int main(int argc, char* argv[]) {
  MessageBoxA(0, "foo", "bar", MB_OK);
  return 0;
}
```

```
99c: msgbox.c:4:3: ir.linker undefined external global MessageBoxA
```
In my understanding, then I should think way to link external symbols?

**Comment by cznic** [comment]
Yes, external symbols must be _defined_ somewhere or linker cannot do its job. Afterwards, it must be also _implemented_ somewhere, if the function defintion is not pure C, but a syscall/WinAPI call.

I'm a Linux programmer, the Windows stuff in cznic/ccir/libc and cznic/virtual was created by @steffengy, maybe he has some valuable advice for you.

**Comment by steffengy** [comment]
`MessageBoxA` is the ANSI variant of [`MessageBox`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms645505(v=vs.85).aspx).
Windows APIs mostly provide an older&simpler ANSI variant (indicated by the `A`) and 
a variant which supports "wide" UTF-16 encoding (indicated by an `W`)

In this case MessageBoxA needs to be added somewhere around here:
https://github.com/cznic/crt/blob/master/windows.go#L153
This file basically contains a list of windows-internal functions which then `go generate`
turns into wrapper functions handling the "windows syscall" internals.

The same has to be done in virtual (which is pretty much 100% identical):
https://github.com/cznic/virtual/blob/master/windows.go#L138
(AFAIK that's what CCIR uses to check if a function is builtin, so without changing virtual
you might still get the linker error, also a good idea to keep them consistent)

**Comment by cznic** [comment]
> (AFAIK that's what CCIR uses to check if a function is builtin, so without changing virtual
you might still get the linker error, also a good idea to keep them consistent)

AFAICT, this is correct.

**Comment by cznic** [comment]
@steffengy 

> In this case MessageBoxA needs to be added somewhere around here:
https://github.com/cznic/crt/blob/master/windows.go#L153

FTR: cznic/crt is what cznic/ccgo uses, but is not (yet) used by cznic/99c and/or cznic/virtual. But I guess the stuff in cznic/ccir/libc for Windows is analogical anyway.

**Comment by mattn** [comment]
On Windows, go have FFI syscall.LoadDLL or syscall.NewDLL.

**Comment by steffengy** [comment]
@mattn 
That's what the wrapping layer uses:
https://github.com/cznic/virtual/blob/master/generator.go#L273

It basically generates the required wrapper functions 
(which convert the given arguments into native pointers & do error handling etc.) 
so that it can map the OP codes in that case to syscalls.

So for your use case it seems that only adding it to virtual is enough,
but the rest of the comment above still applies.

**Comment by cznic** [comment]
Thank you very much @steffengy for your invaluable help!

**Comment by cznic** [comment]
@mattn BTW, if you manage to make that tiny program execute and display the message dialog box, _please_ share the screenshot or link to it here. I will probably setup a virtual Windows box just to be able to try it by myself ;-)

**Comment by mattn** [comment]
@steffengy Cool! So I will be able to compile & run code just use kernel32.dll. Right?

**Comment by steffengy** [comment]
If you want to call a kernel32-API you'll only have to add one single line to virtual and regenerate.

Since I just noticed that MessageBox isn't a kernel32 (but user32) method, you'll have
to modify the generator to support other DLLs as source.

The only difference is basically that you need to generate
```
moduser32           = syscall.NewLazyDLL(\"user32.dll\")
```
and use moduser32 insteadof modkernel32.

I'd suggest changing the generator template syntax from
```
//sys: BOOL   	AreFileApisANSI();
```
to 
```
//sys:kernel32: BOOL   	AreFileApisANSI();
```

Then you'd just generate the loads for the required modules one time at the beginning
and use `mod<MODULENAME>` in the wrapper function.

Let me know if you need further help!
I'd estimate you'll have to write <20 lines of code for that.

**Comment by mattn** [comment]
Now I compile & run following code using https://github.com/cznic/99c/pull/3
```c
#include <windows.h>

int main(int argc, char* argv[]) {
  DWORD written;
  HANDLE hFile = CreateFileA(
	  "hello.txt", GENERIC_WRITE, 0, NULL,
	  CREATE_NEW, FILE_ATTRIBUTE_NORMAL, NULL);
  WriteFile(hFile, "hello world", 11, &written, NULL);
  CloseHandle(hFile);
  return 0;
}
```

```
99c -99extra AnonymousStructFields -99extra WideBitFieldTypes hello.c 
```
I'm happy to see this.

**Comment by mattn** [comment]
So I tried to call MessageBoxA just use kernel32.dll

```c
#include <windows.h>

int main(int argc, char* argv[]) {
  typedef int (*DefMessageBox)(HWND, LPCSTR, LPCSTR, UINT); 
  DefMessageBox pMessageBox;
  HANDLE libuser32 = LoadLibraryA("user32.dll");
  pMessageBox = (DefMessageBox) GetProcAddress(libuser32, "MessageBoxA");
  pMessageBox(0, "Hello World", "99c is awesome", MB_OK); 
  FreeLibrary(libuser32);
  return 0;
}
```
I could comple this but panic.
```
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range


goroutine 1 [running]:
github.com/cznic/virtual.(*cpu).run.func1(0xc042086380)
	c:/dev/godev/src/github.com/cznic/virtual/cpu.go:219 +0x247
panic(0x567760, 0x686450)
	c:/dev/go/src/runtime/panic.go:502 +0x274
github.com/cznic/virtual.(*cpu).run(0xc042086380, 0x2, 0x0, 0x0, 0x0)
	c:/dev/godev/src/github.com/cznic/virtual/cpu.go:236 +0x7da6
github.com/cznic/virtual.New(0xc0421ba000, 0xc042002410, 0x1, 0x1, 0x5c2de0, 0xc042004010, 0x5c2e00, 0xc042004018, 0x5c2e00, 0xc042004020, ...)
	c:/dev/godev/src/github.com/cznic/virtual/virtual.go:73 +0x2c5
github.com/cznic/virtual.Exec(0xc0421ba000, 0xc042002410, 0x1, 0x1, 0x5c2de0, 0xc042004010, 0x5c2e00, 0xc042004018, 0x5c2e00, 0xc042004020, ...)
	c:/dev/godev/src/github.com/cznic/virtual/virtual.go:84 +0xf0
main.main()
	c:/dev/godev/src/github.com/cznic/99c/99run/main.go:70 +0x41a
```

**Comment by steffengy** [comment]
> So I tried to call MessageBoxA just use kernel32.dll


Not sure if related in that case, but see what I wrote [above](https://github.com/cznic/99c/issues/2#issuecomment-335183759)
about `MessageBox` being in user32.

For testing you can just modify windows_impl.go and add the needed code manually and try if that changes anything,.

**Comment by mattn** [comment]
Yes, MessageBox is in user32. I called MessageBox using dynamic loading. If LoadLibrary (kernel32) works correctly, this should work.

**Comment by steffengy** [comment]
Oh didn't see you were using such a nice workaround :)
Yeah that should work.

**Comment by cznic** [comment]
> Yeah that should work.

I dont't think so.

> HANDLE libuser32 = LoadLibraryA("user32.dll");

You cannot load non virtual .dll into the VM. It's loaded to the OS. It's Intel code, not VM code.

**Comment by steffengy** [comment]
> You cannot load non virtual .dll into the VM. It's loaded to the OS. It's Intel code, not VM code.

~~That doesn't load non virtual dlls into the VM,
that loads a DLL via an syscall, which returns a handle. Then he calls a method on that handle via an syscall, it all happens on the native machine.~~

Yeah you're right, that GetProcAddress is what will cause the failure here... 
The address is in host memory, which does not have anything in common with vm-memory for that case

**Comment by mattn** [comment]
> Yeah you're right, that GetProcAddress is what will cause the failure here...
> The address is in host memory, which does not have anything in common with vm-memory for that case

Ah, make sense.

**Comment by mattn** [comment]
closed by https://github.com/cznic/99c/pull/3
